<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_model extends CI_Model
{

    public $table = 'kategori';
    public $id = 'id_kategori';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        
        $this->db->where('terhapus','N');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id_kategori', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_kategori', $q);
	
	$this->db->or_like('aktif', $q);
	$this->db->or_like('terhapus', $q);
	$this->db->from($this->table);
    $this->db->where('terhapus','N');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->where('terhapus','N');
        $this->db->order_by($this->id, $this->order);
     //    $this->db->like('id_kategori', $q);
    	// $this->db->or_like('id_kategori', $q);
    	// $this->db->or_like('nama_kategori', $q);
    	
    	// $this->db->or_like('aktif', $q);
    	//$this->db->or_like('terhapus', $q);
    	$this->db->limit($limit, $start);
            return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    // update data
    function update_1($data,$id)
    {
       $hasil = $this->db->query("UPDATE kategori SET aktif='$data' WHERE id_kategori='$id'");
       return $hasil;
    }

    function update_2($data,$id)
    {
       $hasil = $this->db->query("UPDATE kategori SET aktif='$data' WHERE id_kategori='$id'");
       return $hasil;
    }

    // delete data
    function delete($id)
    {
       $hasil = $this->db->query("UPDATE kategori SET terhapus='Y' WHERE id_kategori='$id'");
       return $hasil;
        // $this->db->where($this->id, $id);
        // $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
//check pk data is exists 

        function is_exist($id){
         $query = $this->db->get_where($this->table, array($this->id => $id));
         $count = $query->num_rows();
         if($count > 0){
            return true;
         }else{
            return false;
         }
        }


}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-02 18:05:28 */
/* http://harviacode.com */