<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rata_tangkapan_ikan_model extends CI_Model
{

    public $table = 'rata_tangkapan_ikan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data rata
    function get_data($id_sungai,$id_jenis_data,$id_tahun, $id_periode,$stasiun=null)
    {
        $this->db->select('*');
        $this->db->join('stasiun', 'rata_tangkapan_ikan.id_stasiun=stasiun.id','left');
        $this->db->where('id_periode', $id_periode);
        $this->db->where('id_tahun', $id_tahun);
        $this->db->where('id_sungai', $id_sungai);
        $this->db->where('id_jenis_data', $id_jenis_data);
        if ($stasiun!=null) 
            $this->db->where('stasiun', $stasiun);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('id_stasiun', $q);
	$this->db->or_like('id_periode', $q);
	$this->db->or_like('rata_rata', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('id_stasiun', $q);
	$this->db->or_like('id_periode', $q);
	$this->db->or_like('rata_rata', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
//check pk data is exists 

        function is_exist($id){
         $query = $this->db->get_where($this->table, array($this->id => $id));
         $count = $query->num_rows();
         if($count > 0){
            return true;
         }else{
            return false;
         }
        }


}

/* End of file Rata_tangkapan_ikan_model.php */
/* Location: ./application/models/Rata_tangkapan_ikan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-07 05:34:33 */
/* http://harviacode.com */