<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Variabel_model extends CI_Model
{

    public $table = 'variabel';
    public $id = 'id_variabel';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id_grafik
    function get_by_id_grafik($id,$limit)
    {
        $this->db->where('id_grafik', $id);
        $this->db->limit(1,$limit);
        return $this->db->get($this->table)->row();
    }

    // get data by id_grafik with result
    function get_by_id_grafik_all($id)
    {
        $this->db->where('id_grafik', $id);
        return $this->db->get($this->table)->result();
    }
    
    
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_variabel', $q);
	$this->db->or_like('id_variabel', $q);
	$this->db->or_like('id_grafik', $q);
	$this->db->or_like('nilai', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_variabel', $q);
	$this->db->or_like('id_variabel', $q);
	$this->db->or_like('id_grafik', $q);
	$this->db->or_like('nilai', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
    
//check pk data is exists 

        function is_exist($id){
            $this->db->join('grafik', 'grafik.id_grafik=variabel.id_grafik', 'left');
            $this->db->where('grafik.id_download', $id);
            $count= $this->db->get($this->table)->num_rows();

        //  $query = $this->db->get_where($this->table, array($this->id => $id));
        //  $count = $query->num_rows();
         if($count > 0){
            return true;
         }else{
            return false;
         }
        }


}

/* End of file Variabel_model.php */
/* Location: ./application/models/Variabel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-11 00:55:09 */
/* http://harviacode.com */